### ISSUE TITLE
生成的fbx抖动较多

### ISSUE THREAD

**Issue by richieliuse** [Luke-Luo1/POPDG#7]
@Luke-Luo1 感谢杰出的工作！我在使用源码复现论文结果的时候发现，最终转换生成的fbx在blender中播放时人体会有不停的抖动，相比较edge的生成结果在播放时没有这个问题。请问可能是什么原因造成的？

**Comment by Luke-Luo1** [comment]
非常感谢您的反馈，这个问题主要是数据库差异所造成的。正如在文中和Readme所指出的那样，依靠3D姿态估计来提取舞蹈特征所构成的PopDanceSet的舞蹈质量，还是难比有九个环绕相机位来提取舞蹈数据的AIST++，故其本身数据库的舞蹈就会有抖动现象。

**Comment by GuangtaoLyu** [comment]
有哪些样本质量是比较高的吗？ 我看readme里面的就很好。 而从给的高质量数据集列表里面可视化的，很多还是比较差。。

**Comment by Luke-Luo1** [comment]
The samples listed in the “high-quality dataset” are already relatively better compared to the full dataset. However, since the poses are extracted using monocular pose estimation, some degree of jitter is inevitable.

That said, all these samples have been processed with outlier removal, Gaussian smoothing, and some being processed with root joint stabilization, so there shouldn’t be many severe flickering or distortion issues. It’s possible that the currently uploaded files are older origin versions — I’ll ask my colleague to re-upload the fully preprocessed data soon, though since both my junior collaborator and I have already graduated, it may take some time to locate the files.

Appreciate your feedback!

**Comment by GuangtaoLyu** [comment]
多谢，期待。












吕光涛(GuangtaoLyu)
***@***.***






---原始邮件---
发件人: "Zhenye ***@***.***&gt;
发送时间: 2025年7月14日(周一) 晚上11:01
收件人: ***@***.***&gt;;
抄送: "Guangtao Lyu ( 吕光涛 ***@***.******@***.***&gt;;
主题: Re: [Luke-Luo1/POPDG] 生成的fbx抖动较多 (Issue #7)


Luke-Luo1 left a comment (Luke-Luo1/POPDG#7)
 
The samples listed in the “high-quality dataset” are already relatively better compared to the full dataset. However, since the poses are extracted using monocular pose estimation, some degree of jitter is inevitable.
 
That said, all these samples have been processed with outlier removal, Gaussian smoothing, and some being processed with root joint stabilization, so there shouldn’t be many severe flickering or distortion issues. It’s possible that the currently uploaded files are older origin versions — I’ll ask my colleague to re-upload the fully preprocessed data soon, though since both my junior collaborator and I have already graduated, it may take some time to locate the files.
 
Appreciate your feedback!
